// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PartnerFinder.Data;

#nullable disable

namespace PartnerFinder.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260702125534_AddTargetingSignals")]
    partial class AddTargetingSignals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("PartnerFinder.Models.Partner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AiInfrastructureScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AiInfrastructureSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AiModelInferenceSetup")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AiServerBuildCapability")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AiSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AmdGpuExperience")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BreakFixCapability")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Certifications")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("CiscoPartnerStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactTitle")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<bool>("CoolingPowerPlanningCapability")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("DataCenterExperience")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DellPartnerStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EdgeAiDeploymentCapability")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EquipmentLeasingSignal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FollowUpAction")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("GpuWorkstationBuildCapability")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HpePartnerStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ImacCapability")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkedIn")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<bool>("LinuxDockerKubernetesCapability")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LocalLlmDeploymentCapability")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MainServices")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ManualReviewStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MicrosoftPartnerStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("NetworkSupportCapability")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("NvidiaGpuExperience")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NvidiaJetsonExperience")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OnPremAiDeploymentExperience")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<int>("QualificationScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecommendedLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ServerSupportCapability")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServiceCategory")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SmallAiClusterExperience")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SmartHandsCapability")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SmeFocusSignal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<bool>("StorageSupportCapability")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Website")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyName");

                    b.HasIndex("Country");

                    b.HasIndex("RecommendedLevel");

                    b.ToTable("Partners");
                });
#pragma warning restore 612, 618
        }
    }
}
